# Generated by Django 5.2.7 on 2025-11-01 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blackoutdate",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blackout_dates",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="properties.viewtype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blackoutdate",
            unique_together={("property", "date")},
        ),
    ]
