# Generated by Django 5.2.7 on 2025-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_new_user",
                    models.BooleanField(
                        default=True, verbose_name="New User Registration"
                    ),
                ),
                (
                    "notify_new_booking",
                    models.BooleanField(default=True, verbose_name="New Booking"),
                ),
                (
                    "notify_new_vendor",
                    models.BooleanField(
                        default=True, verbose_name="New Vendor Application"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
